Models/LoginTable.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginTable
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

Controllers/AdminController.cs
using ProductMarket.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ProductMarket.Controllers
{
    public class AdminController : Controller
    {
        ProductsEntities connect = new ProductsEntities();
        public ActionResult Login()
        {
            if (User.Identity.Name != "")
            { FormsAuthentication.SignOut(); }

            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginTable login)
        {
            if (login.Username != null)
            {
                if (login.Password != null)
                {
                    var bilgi = connect.LoginTable.FirstOrDefault(m => m.Username == login.Username && m.Password == login.Password);

                    if (bilgi != null)
                    {
                        FormsAuthentication.RedirectFromLoginPage(bilgi.ID.ToString(), false);
                        return RedirectToAction("Index", "Product");
                    }
                    else
                    {
                        ViewBag.uyari = "Bilgilerinizi kontrol ediniz.";
                    }
                }
                else
                {
                    ViewBag.uyari = "Şifrenizi yazınız.";
                }
            }
            else
            {
                ViewBag.uyari = "Kullanıcı adınızı yazınız.";
            }

            return View();
        }
    }
}

Views/Admin/Login.cshtml
@model ProductMarket.Models.LoginTable
    @{
        ViewBag.Title = "Login";
    }
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Page Title - Admin Panel</title>
    <link href="~/Css2/styles.css" rel="stylesheet" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header"><h3 class="text-center font-weight-light my-4">Giriş Sayfası</h3></div>
                                <div class="card-body">
                                    @using (Html.BeginForm("Login", "Admin", FormMethod.Post))
                                    {

                                        <form>
                                            <div class="form-group"><label class="small mb-1" for="inputEmailAddress">Email</label>@Html.TextBoxFor(m => m.Username, new { @class = "form-control", @placeholder = "Kullanıcı Adı" })</div>
                                            <div class="form-group"><label class="small mb-1" for="inputPassword">Şifre</label> @Html.TextBoxFor(m => m.Password, new { @class = "form-control", type = "password", @placeholder = "Şifre" })</div>
                                            <div class="form-group">
                                                <div class="custom-control custom-checkbox"><input class="custom-control-input" id="rememberPasswordCheck" type="checkbox" /><label class="custom-control-label" for="rememberPasswordCheck">Şifre hatırlansın</label></div>
                                            </div>
                                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0"><button class="btn btn-success" type="submit">Giriş</button></div>

                                            <p style="color:red">@ViewBag.uyari</p>
                                        </form>
                                    }
                                </div>
                                <div class="card-footer text-center">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2019</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>++,
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js"></script>
</body>
</html>